# Generated by Django 2.2.4 on 2020-05-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
