# Generated by Django 2.2.4 on 2020-05-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_author_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authors_in_book',
            new_name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
