# Generated by Django 2.2.4 on 2020-05-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breweries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
