# Generated by Django 2.2.4 on 2020-05-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='description',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
