# Generated by Django 2.2.4 on 2020-05-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0004_auto_20200515_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(),
        ),
    ]
